interface = "en1"
pkt_len = 2000
filter = "tcp"

# pcap_file = "~/misc/https.pcap"
store_path = "/Users/lch/misc/nsave_data/"

# 写磁盘线程个数
thread_num = 2

pkt_channel_size = 2048
msg_channel_size = 1024
# 微秒。500毫秒
timer_intervel = 500000000
# 毫秒
writer_empty_sleep = 5
# 毫秒
aide_empty_sleep = 100

# 16M 1024 * 1024 * 16
pool_size = 16777216
# 2M 1024 * 1024 * 2
file_size = 2097152
# 80k 1024 * 80
chunk_size = 81920

ci_buff_size = 1024
ti_buff_size = 1024

flow_max_table_capacity = 1024
# 微妙。 10秒
flow_node_timeout = 10000000000
flow_max_seq_gap = 8
