[package]
name = "ebpf"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "nsave"
path = "src/main.rs"
